# Generated by Django 3.0.5 on 2021-06-22 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210622_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Оценка может быть от 1 до 10.'), django.core.validators.MaxValueValidator(10, message='Оценка может быть от 1 до 10.')], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='year',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(2021, message='Год больше текущего.')], verbose_name='Год выпуска'),
        ),
    ]
