# Generated by Django 3.0.5 on 2021-06-13 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210613_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(help_text='Напишите кратко о себе', verbose_name='description'),
        ),
    ]
