# Generated by Django 3.0.5 on 2021-06-16 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210616_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='titles',
            options={'ordering': ('-name',), 'verbose_name': 'Произведение', 'verbose_name_plural': 'Произведения'},
        ),
    ]
