# Generated by Django 3.0.5 on 2021-06-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210615_2228'),
        ('api', '0017_auto_20210615_2134'),
    ]

    operations = [
    ]
